### ISSUE TITLE
Ax88772a  not work

### ISSUE THREAD

**Issue by xumenghe1989** [karosium/asix_eepromtool#1] opened 2020-07-11 00:59 UTC
I test ax88772a Modify pid from  772a to 7720 Not working
Eeprom size 256
The eeprom Has been modified
There is no change in the device id in the device manager

**Comment by karosium** [comment] 2020-07-11 09:48
On my chip the VID/PID appeared multiple times and all instances had to be changed. Can you find any remaining copies of the PID bytes in the image?

**Comment by xumenghe1989** [comment] 2020-07-11 10:06
It appeared on my chip twice
I modified everything, but it still didn't work.

**Comment by karosium** [comment] 2020-07-11 13:08
I checked mine and had two instances as well at 0x48 and 0x88, after modifying them and reconnecting the VID/PID changed accordingly. Maybe there's a bit that controls whether the EEPROM based VID/PID is used and it's disabled on yours but that's just a guess. I'll keep this open for comments.

The EEPROM dump from my B chip for comparison:
```
00000000: 5a15 75ec 1220 2729 6000 426e 1c5b 0409  Z.u.. ')`.Bn.[..
00000010: 2260 1271 0e19 043d 043d 043d 043d 0580  "`.q...=.=.=.=..
00000020: 0600 e010 2442 1240 2749 ffff 0000 ffff  ....$B.@'I......
00000030: 09c0 030e 0030 0030 0030 0030 0030 0031  .....0.0.0.0.0.1
00000040: 0112 0200 ffff 4000 0b95 772b 0001 0201  ......@...w+....
00000050: 0103 0209 0027 0101 a004 0964 0004 0300  .....'.....d....
00000060: ffff 0700 0507 0381 0008 070b 8205 0002  ................
00000070: 0002 0507 0203 0200 ff00 0304 0030 ffff  .............0..
00000080: 0112 0200 ffff 0800 0b95 772b 0001 0201  ..........w+....
00000090: 0103 0209 0027 0101 a004 0964 0004 0300  .....'.....d....
000000a0: ffff 0700 0507 0381 0008 07a0 8205 4002  ..............@.
000000b0: 0000 0507 0203 0040 dd00 ffff aaaa bbbb  .......@........
000000c0: 0322 0041 0053 0049 0058 0020 0045 006c  .".A.S.I.X. .E.l
000000d0: 0065 0063 002e 0020 0043 006f 0072 0070  .e.c... .C.o.r.p
000000e0: 002e 0312 0041 0058 0038 0038 0037 0037  .....A.X.8.8.7.7
000000f0: 0032 0042 ffff ffff ffff ffff ffff ffff  .2.B............
```

**Comment by xumenghe1989** [comment] 2020-07-11 13:28
hi this is my code，i modify it from 772A to 7720
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<body>
<pre>
<span class="offsetheader">Offset(d) 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15</span>
<span class="offsetcol">00000000</span>  <span class="hexcol">5A 15 71 ED 12 20 27 29 0E 00 00 AA 72 A4 04 09</span>  <span class="textcol">Z.qí. ')...ªr¤..</span>
<span class="offsetcol">00000016</span>  <span class="hexcol">22 60 12 71 0E 19 04 3D 04 3D 04 3D 04 3D 05 9C</span>  <span class="textcol">&quot;`.q...=.=.=.=.œ</span>
<span class="offsetcol">00000032</span>  <span class="hexcol">06 00 E0 10 24 54 12 40 27 49 FF FF 00 00 FF FF</span>  <span class="textcol">..à.$T.@'Iÿÿ..ÿÿ</span>
<span class="offsetcol">00000048</span>  <span class="hexcol">FF FF 03 0E 00 30 00 30 00 30 00 30 00 30 00 32</span>  <span class="textcol">ÿÿ...0.0.0.0.0.2</span>
<span class="offsetcol">00000064</span>  <span class="hexcol">01 12 02 00 FF FF 40 00 0B 95 77 20 00 01 02 01</span>  <span class="textcol">....ÿÿ@..•w ....</span>
<span class="offsetcol">00000080</span>  <span class="hexcol">01 03 02 09 00 27 01 01 E0 04 09 7D 00 04 03 00</span>  <span class="textcol">.....'..à..}....</span>
<span class="offsetcol">00000096</span>  <span class="hexcol">FF FF 07 00 05 07 03 81 00 08 07 0B 82 05 00 02</span>  <span class="textcol">ÿÿ..........‚...</span>
<span class="offsetcol">00000112</span>  <span class="hexcol">00 02 05 07 02 03 02 00 FF 00 03 04 00 30 FF FF</span>  <span class="textcol">........ÿ....0ÿÿ</span>
<span class="offsetcol">00000128</span>  <span class="hexcol">01 12 02 00 FF FF 08 00 0B 95 77 20 00 01 02 01</span>  <span class="textcol">....ÿÿ...•w ....</span>
<span class="offsetcol">00000144</span>  <span class="hexcol">01 03 02 09 00 27 01 01 E0 04 09 7D 00 04 03 00</span>  <span class="textcol">.....'..à..}....</span>
<span class="offsetcol">00000160</span>  <span class="hexcol">FF FF 07 00 05 07 03 81 00 08 07 A0 82 05 40 02</span>  <span class="textcol">ÿÿ......... ‚.@.</span>
<span class="offsetcol">00000176</span>  <span class="hexcol">00 00 05 07 02 03 00 40 DD 00 FF FF AA AA BB BB</span>  <span class="textcol">.......@Ý.ÿÿªª»»</span>
<span class="offsetcol">00000192</span>  <span class="hexcol">03 22 00 41 00 53 00 49 00 58 00 20 00 45 00 6C</span>  <span class="textcol">.&quot;.A.S.I.X. .E.l</span>
<span class="offsetcol">00000208</span>  <span class="hexcol">00 65 00 63 00 2E 00 20 00 43 00 6F 00 72 00 70</span>  <span class="textcol">.e.c... .C.o.r.p</span>
<span class="offsetcol">00000224</span>  <span class="hexcol">00 2E 03 12 00 41 00 58 00 38 00 38 00 78 00 37</span>  <span class="textcol">.....A.X.8.8.x.7</span>
<span class="offsetcol">00000240</span>  <span class="hexcol">00 32 00 41 FF FF FF FF FF FF FF FF FF FF FF FF</span>  <span class="textcol">.2.Aÿÿÿÿÿÿÿÿÿÿÿÿ</span>
</pre>
<p class="generatorinfo">Generated by <a href="https://mh-nexus.de/hxd/" class="generatorlink">HxD</a></p>
</body>
</html>
`

**Comment by karosium** [comment] 2020-09-25 20:16
Hi,

Someone tested this with an AX88772A last month and it worked for them: https://mastodon.online/@gcc_addict/104683023150830769

Could you read the eeprom from your device and double-check that your modifications were written properly and it's still coming up with the old VID/PID regardless?

**Comment by karosium** [comment] 2020-11-04 00:15
If anyone is still having this issue leave a comment and I'll reopen. Closing for now.

**Comment by stanwebber** [comment] 2020-12-16 20:26
i'm unable to modify the pid on a sabrent usb adapter from 0b95:772b to 0b95:7720.  0b95:772b shows up twice in my dump, but modifying both or 1 or the other has no effect.  0b95:802b also shows up and i once saw the adapter identified with this vid:pid (after writing new eeprom), but only that single time and never since.  i have re-read the eeprom from the adapter so i know my changes were committed.  any ideas why it isn't working?  do you think i could flash a donor eeprom from a different ax88772b adapter?


00 15 1d f8 12 20 35 29 00 00 00 00 b5 51 04 09 22 6e 12 7f 0e 19 04 44 04 44 04 44 04 44 05 80 06 00 e0 10 24
42 12 47 35 50 ff ff 00 00 ff ff 08 88 03 0e 00 30 00 30 00 30 00 43 00 30 00 31 01 12 02 00 ff ff 40 00 0b 95
77 2b 00 01 02 01 01 03 02 09 00 35 01 01 80 04 09 64 00 04 05 00 ff ff 07 00 05 07 03 81 00 08 07 0b 82 05 00
02 00 02 05 07 02 03 02 00 07 00 84 05 00 02 00 02 05 07 02 05 02 00 ff 00 0b 95 77 2b ff ff 01 12 02 00 ff ff
08 00 0b 95 80 2b 00 64 02 01 01 03 02 09 00 35 01 01 e0 04 09 02 00 04 05 00 ff ff 07 00 05 07 03 81 00 08 07
a0 82 05 40 02 00 00 05 07 00 41 00 53 00 49 00 58 00 20 00 45 00 6c 00 65 00 63 00 2e 00 20 00 43 00 6f 00 72
00 70 00 2e 03 12 00 41 00 58 00 38 00 38 00 37 00 37 00 32 00 42 ff ff ff ff ff ff ff ff ff ff ff ff

**Comment by karosium** [comment] 2020-12-16 21:40
Thanks for confirming that this isn't an eeprom write problem.

I tried looking into it but couldn't find anything conclusive.

Some ASIX chips have this feature but it's not specifically mentioned for the AX88772A
" * Supports embedded eFuse (64-byte) to store USB Device Descriptors, Node-ID, etc to save external EEPROM"

It is mentioned for the AX88172A though, which is lumped together with the AX88772A in this PDF:
https://pdf.dzsc.com/200871/200807010904381995.pdf 

so it could still be the cause but it could also be something in the eeprom disabling the use of the ID, no clue.

No idea what the A chip would do with the B chip's eeprom contents either, unfortunately. Try at your own risk.

I've reopened this, hopefully someone who managed to mod the A chip can chime in at some point.

**Comment by stanwebber** [comment] 2020-12-16 21:54
sorry for the confusion--my adapter is a ax88772B, not A.  since your readme.md indicated you tested with a 2B i was hoping you might have some additional insight.  incidentally, i also tried this with an ax881720 adapter and the pid change worked, but the device didn't completely function with the ax887720 drivers.

**Comment by karosium** [comment] 2020-12-16 22:26
Oh, I see the B in the dump now. I guess that means this isn't specific to the A chips.

I just flashed it to my device to test. 
first connection after flashing:
Bus 001 Device 023: ID 0b95:802b ASIX Electronics Corp. 
second (and every other) connection:
Bus 001 Device 024: ID 0b95:772b ASIX Electronics Corp. AX88772B

Strange. But even with your eeprom contents if I change the appropriate bytes my vid/pid changes:

Bus 001 Device 046: ID 0b95:77aa ASIX Electronics Corp. 

So I think my theory above about permanent eFuse VID/PID configuration on some adapters is unfortunately correct and whether changing eeprom content does anything for VID/PID/MAC will depend on how the manufacturer decided to configure the device.

**Comment by karosium** [comment] 2020-12-17 14:28
Exchanged some emails and it was confirmed that even with my eeprom contents the chip's VID/PID could not be changed so there are definitely chips with permanently set VID/PID that ignore eeprom contents. Info added to repo readme.

**Closed by karosium** 2020-12-17 14:28 UTC
Labels: help wanted
